name: Deploy GitBook
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          npm install -g honkit
          cd notes
          honkit build

      # 新增：复制源文件
      - name: Copy Source Files
        run: |
          mkdir -p temp/notes
          cp -r notes/_book/* temp/notes/
          cp notes/README.md notes/SUMMARY.md temp/notes/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp/notes    # 改为发布临时目录
          destination_dir: notes
