name: Deploy GitBook
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          npm install -g honkit
          cd notes  # 进入 notes 目录
          # 检查文件是否存在
          ls -la
          # 安装依赖（如果需要）
          npm install
          # 直接在 notes 目录构建
          honkit build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./notes/_book  # 这个路径是对的，因为 _book 在 notes 目录下
          destination_dir: notes      # 部署到 gh-pages 的 notes 目录
